import toyotaRav4 from '../assets/toyotaRav4.webp'
import bmw3series from '../assets/bmw3series.webp'
import volkswagenTcross from '../assets/volkswagenTcross.jpg'
import cadillacEscalade from '../assets/cadillacEscalade.jpg'
import bmw4Series from '../assets/bmw4Series.webp'
import mustang from '../assets/mustang.avif'
import bmw7series from '../assets/bmw7series.jpg'
import bmwi5 from '../assets/bmwi5.jpg'
import bmwi7 from '../assets/bmwi7.jpg'
import bmwM2 from '../assets/bmwM2.jpg'
import toyotaGrCorolla from '../assets/toyotaGrCorolla.jpg'
import toyotaGrSupra from '../assets/toyotaGrSupra.jpg'
import toyotaGrandHighlander from '../assets/toyotaGrandHighlander.jpg'
import toyotaBz4x from '../assets/toyotaBz4x.jpg'
import toyotaLandCruiser from '../assets/toyotaLandCruiser.jpg'
import volkswagenAtlas from '../assets/volkswagenAtlas.jpg'
import volkswagenGolfR from '../assets/volkswagenGolfR.jpg'
import volkswagenId7 from '../assets/volkswagenId7.jpg'
import volkswagenJetta from '../assets/volkswagenJetta.jpg'
import volkswagenTaiguan from '../assets/volkswagenTaiguan.jpg'
import cadillacct4 from '../assets/cadillacct4.jpg'
import cadillacLyriq from '../assets/cadillacLyriq.jpg'
import cadillacCelestiq from '../assets/cadillacCelestiq.jpg'
import cadillacCt5 from '../assets/cadillacCt5.jpg'
import cadillacXt4 from '../assets/cadillacXt4.jpg'
import fordMustang1 from '../assets/fordMustang1.jpg'
import fordEdge from '../assets/fordEdge.jpg'
import fordExplorer from '../assets/fordExplorer.jpg'
import fordF150Raptor from '../assets/fordF150Raptor.jpg'
import fordFocusRs from '../assets/fordFocusRs.jpg'

export const allCars = [
    {
        image: fordFocusRs,
        name: "Ford Focus RS",
        year: 2019,
        brand: "Ford",
        seats: "4 People",
        fuel: "Gasoline",
        km: "15.4km / 1-litre",
        type: "Automatic",
        rent: 500,
    },
    {
        image: fordF150Raptor,
        name: "Ford F-150 Raptor",
        year: 2021,
        brand: "Ford",
        seats: "4 People",
        fuel: "Gasoline",
        km: "5.5km / 1-litre",
        type: "Automatic",
        rent: 510,
    },
    {
        image: fordExplorer,
        name: "Ford Explorer",
        year: 2021,
        brand: "Ford",
        seats: "4 People",
        fuel: "Gasoline",
        km: "7.5km / 1-litre",
        type: "Automatic",
        rent: 550,
    },
    {
        image: fordEdge,
        name: "Ford Edge",
        year: 2020,
        brand: "Ford",
        seats: "4 People",
        fuel: "Gasoline",
        km: "10.5km / 1-litre",
        type: "Automatic",
        rent: 450,
    },
    {
        image: fordMustang1,
        name: "Ford Mustang",
        year: 2021,
        brand: "Ford",
        seats: "2 People",
        fuel: "Gasoline",
        km: "5km / 1-litre",
        type: "Automatic",
        rent: 750,
    },
    {
        image: cadillacXt4  ,
        name: "Cadillac XT4",
        year: 2023,
        brand: "Cadillac",
        seats: "4 People",
        fuel: "Gasoline",
        km: "13.4km / 1-litre",
        type: "Automatic",
        rent: 450,
    },
    {
        image: cadillacCt5  ,
        name: "Cadillac CT5",
        year: 2022,
        brand: "Cadillac",
        seats: "4 People",
        fuel: "Gasoline",
        km: "10.4km / 1-litre",
        type: "Automatic",
        rent: 550,
    },
    {
        image: cadillacCelestiq  ,
        name: "Cadillac Celestiq",
        year: 2023,
        brand: "Cadillac",
        seats: "4 People",
        fuel: "Electric",
        km: "180km / 1-full",
        type: "Automatic",
        rent: 650,
    },
    {
        image: cadillacLyriq,
        name: "Cadillac Lyriq",
        year: 2021,
        brand: "Cadillac",
        seats: "4 People",
        fuel: "Electric",
        km: "200km / 1-full",
        type: "Automatic",
        rent: 650,
    },
    {
        image: cadillacct4,
        name: "Cadillac CT4",
        year: 2019,
        brand: "Cadillac",
        seats: "4 People",
        fuel: "Electric",
        km: "350km / 1-full",
        type: "Automatic",
        rent: 450,
    },
    {
        image: volkswagenTaiguan,
        name: "Volkswagen Tiguan",
        year: 2022,
        brand: "Volkswagen",
        seats: "4 People",
        fuel: "Electric",
        km: "300km / 1-full",
        type: "Automatic",
        rent: 300,
    },
    {
        image: volkswagenJetta,
        name: "Volkswagen Jetta",
        year: 2021,
        brand: "Volkswagen",
        seats: "4 People",
        fuel: "Electric",
        km: "200km / 1-full",
        type: "Automatic",
        rent: 510,
    },
    {
        image: volkswagenId7,
        name: "Volkswagen ID.7",
        year: 2023,
        brand: "Volkswagen",
        seats: "4 People",
        fuel: "Electric",
        km: "200km / 1-full",
        type: "Automatic",
        rent: 500,
    },
    {
        image: volkswagenGolfR,
        name: "Volkswagen Golf R",
        year: 2020,
        brand: "Volkswagen",
        seats: "4 People",
        fuel: "Gasoline",
        km: "15km / 1-litre",
        type: "Automatic",
        rent: 400,
    },
    {
        image: volkswagenAtlas,
        name: "Volkswagen Atlas",
        year: 2022,
        brand: "Volkswagen",
        seats: "7 People",
        fuel: "Gasoline",
        km: "11km / 1-litre",
        type: "Automatic",
        rent: 450,
    },
    {
        image: toyotaLandCruiser,
        name: "Toyota Land Cruiser",
        year: 2021,
        brand: "Toyota",
        seats: "7 People",
        fuel: "Gasoline",
        km: "8km / 1-litre",
        type: "Manuel",
        rent: 600,
    },
    {
        image: toyotaBz4x,
        name: "Toyota bZ4X",
        year: 2021,
        brand: "Toyota",
        seats: "4 People",
        fuel: "Electric",
        km: "200km / 1-full",
        type: "Automatic",
        rent: 550,
    },
    {
        image: toyotaGrandHighlander,
        name: "Toyota Grand Highlander",
        year: 2023,
        brand: "Toyota",
        seats: "7 People",
        fuel: "Hybrid",
        km: "8km / 1-litre",
        type: "Automatic",
        rent: 650,
    },
    {
        image: toyotaGrSupra,
        name: "Toyota GR Supra",
        year: 2022,
        brand: "Toyota",
        seats: "2 People",
        fuel: "Hybrid",
        km: "5km / 1-litre",
        type: "Automatic",
        rent: 750,
    },
    {
        image: toyotaRav4,
        name: "Toyota RAV4",
        year: 2021,
        brand: "Toyota",
        seats: "4 People",
        fuel: "Hybrid",
        km: "6.1km / 1-litre",
        type: "Automatic",
        rent: 440,
    },
    {
        image: toyotaGrCorolla,
        name: "Toyota GR Corolla",
        year: 2022,
        brand: "Toyota",
        seats: "4 People",
        fuel: "Hybrid",
        km: "11km / 1-litre",
        type: "Automatic",
        rent: 450,
    },
    {
        image: bmw3series,
        name: "BMW 3 Series",
        year: 2019,
        brand: "BMW",
        seats: "4 People",
        fuel: "Gasoline",
        km: "8.2km / 1-litre",
        type: "Automatic",
        rent: 350,
    },
    {
        image: volkswagenTcross,
        name: "Volkswagen T-Cross",
        year: 2020,
        brand: "Volkswagen",
        seats: "4 People",
        fuel: "Gasoline",
        km: "5.3km / 1-litre",
        type: "Automatic",
        rent: 400,
    },
    {
        image: cadillacEscalade,
        name: "Cadillac Escalade",
        year: 2020,
        brand: "Cadillac",
        seats: "7 People",
        fuel: "Gasoline",
        km: "7.7km / 1-litre",
        type: "Automatic",
        rent: 620,
    },
    {
        image: bmw4Series,
        name: "BMW 4 Series GTI",
        year: 2021,
        brand: "BMW",
        seats: "4 People",
        fuel: "Gasoline",
        km: "7.6km / 1-litre",
        type: "Automatic",
        rent: 530,
    },
    {
        image: mustang,
        name: "Ford Mustang",
        year: 1967,
        brand: "Ford",
        seats: "2 People",
        fuel: "Electric",
        km: "7.5km / 1-litre",
        type: "Manuel",
        rent: 700,
    },
    {
        image: bmw7series,
        name: "BMW 7 Series",
        year: 2023,
        brand: "BMW",
        seats: "4 People",
        fuel: "Gasoline",
        km: "9km / 1-litre",
        type: "Automatic",
        rent: 550,
    },
    {
        image: bmwi5,
        name: "BMW i5",
        year: 2021,
        brand: "BMW",
        seats: "4 People",
        fuel: "Gasoline",
        km: "10km / 1-litre",
        type: "Automatic",
        rent: 600,
    },
    {
        image: bmwi7,
        name: "BMW i7",
        year: 2022,
        brand: "BMW",
        seats: "4 People",
        fuel: "Electric",
        km: "10km / 1-litre",
        type: "Automatic",
        rent: 650,
    },
    {
        image: bmwM2,
        name: "BMW M2",
        year: 2023,
        brand: "BMW",
        seats: "2 People",
        fuel: "Electric",
        km: "5.6km / 1-litre",
        type: "Automatic",
        rent: 670,
    },

    // copy 

    {
        image: fordFocusRs,
        name: "Ford Focus RS",
        year: 2019,
        brand: "Ford",
        seats: "4 People",
        fuel: "Gasoline",
        km: "15.4km / 1-litre",
        type: "Automatic",
        rent: 500,
    },
    {
        image: fordF150Raptor,
        name: "Ford F-150 Raptor",
        year: 2021,
        brand: "Ford",
        seats: "4 People",
        fuel: "Gasoline",
        km: "5.5km / 1-litre",
        type: "Automatic",
        rent: 510,
    },
    {
        image: fordExplorer,
        name: "Ford Explorer",
        year: 2021,
        brand: "Ford",
        seats: "4 People",
        fuel: "Gasoline",
        km: "7.5km / 1-litre",
        type: "Automatic",
        rent: 550,
    },
    {
        image: fordEdge,
        name: "Ford Edge",
        year: 2020,
        brand: "Ford",
        seats: "4 People",
        fuel: "Gasoline",
        km: "10.5km / 1-litre",
        type: "Automatic",
        rent: 450,
    },
    {
        image: fordMustang1,
        name: "Ford Mustang",
        year: 2021,
        brand: "Ford",
        seats: "2 People",
        fuel: "Gasoline",
        km: "5km / 1-litre",
        type: "Automatic",
        rent: 750,
    },
    {
        image: cadillacXt4  ,
        name: "Cadillac XT4",
        year: 2023,
        brand: "Cadillac",
        seats: "4 People",
        fuel: "Gasoline",
        km: "13.4km / 1-litre",
        type: "Automatic",
        rent: 450,
    },
    {
        image: cadillacCt5  ,
        name: "Cadillac CT5",
        year: 2022,
        brand: "Cadillac",
        seats: "4 People",
        fuel: "Gasoline",
        km: "10.4km / 1-litre",
        type: "Automatic",
        rent: 550,
    },
    {
        image: cadillacCelestiq  ,
        name: "Cadillac Celestiq",
        year: 2023,
        brand: "Cadillac",
        seats: "4 People",
        fuel: "Electric",
        km: "180km / 1-full",
        type: "Automatic",
        rent: 650,
    },
    {
        image: cadillacLyriq,
        name: "Cadillac Lyriq",
        year: 2021,
        brand: "Cadillac",
        seats: "4 People",
        fuel: "Electric",
        km: "200km / 1-full",
        type: "Automatic",
        rent: 650,
    },
    {
        image: cadillacct4,
        name: "Cadillac CT4",
        year: 2019,
        brand: "Cadillac",
        seats: "4 People",
        fuel: "Electric",
        km: "350km / 1-full",
        type: "Automatic",
        rent: 450,
    },
    {
        image: volkswagenTaiguan,
        name: "Volkswagen Tiguan",
        year: 2022,
        brand: "Volkswagen",
        seats: "4 People",
        fuel: "Electric",
        km: "300km / 1-full",
        type: "Automatic",
        rent: 300,
    },
    {
        image: volkswagenJetta,
        name: "Volkswagen Jetta",
        year: 2021,
        brand: "Volkswagen",
        seats: "4 People",
        fuel: "Electric",
        km: "200km / 1-full",
        type: "Automatic",
        rent: 510,
    },
    {
        image: volkswagenId7,
        name: "Volkswagen ID.7",
        year: 2023,
        brand: "Volkswagen",
        seats: "4 People",
        fuel: "Electric",
        km: "200km / 1-full",
        type: "Automatic",
        rent: 500,
    },
    {
        image: volkswagenGolfR,
        name: "Volkswagen Golf R",
        year: 2020,
        brand: "Volkswagen",
        seats: "4 People",
        fuel: "Gasoline",
        km: "15km / 1-litre",
        type: "Automatic",
        rent: 400,
    },
    {
        image: volkswagenAtlas,
        name: "Volkswagen Atlas",
        year: 2022,
        brand: "Volkswagen",
        seats: "7 People",
        fuel: "Gasoline",
        km: "11km / 1-litre",
        type: "Automatic",
        rent: 450,
    },
    {
        image: toyotaLandCruiser,
        name: "Toyota Land Cruiser",
        year: 2021,
        brand: "Toyota",
        seats: "7 People",
        fuel: "Gasoline",
        km: "8km / 1-litre",
        type: "Manuel",
        rent: 600,
    },
    {
        image: toyotaBz4x,
        name: "Toyota bZ4X",
        year: 2021,
        brand: "Toyota",
        seats: "4 People",
        fuel: "Electric",
        km: "200km / 1-full",
        type: "Automatic",
        rent: 550,
    },
    {
        image: toyotaGrandHighlander,
        name: "Toyota Grand Highlander",
        year: 2023,
        brand: "Toyota",
        seats: "7 People",
        fuel: "Hybrid",
        km: "8km / 1-litre",
        type: "Automatic",
        rent: 650,
    },
    {
        image: toyotaGrSupra,
        name: "Toyota GR Supra",
        year: 2022,
        brand: "Toyota",
        seats: "2 People",
        fuel: "Hybrid",
        km: "5km / 1-litre",
        type: "Automatic",
        rent: 750,
    },
    {
        image: toyotaRav4,
        name: "Toyota RAV4",
        year: 2021,
        brand: "Toyota",
        seats: "4 People",
        fuel: "Hybrid",
        km: "6.1km / 1-litre",
        type: "Automatic",
        rent: 440,
    },
    {
        image: toyotaGrCorolla,
        name: "Toyota GR Corolla",
        year: 2022,
        brand: "Toyota",
        seats: "4 People",
        fuel: "Hybrid",
        km: "11km / 1-litre",
        type: "Automatic",
        rent: 450,
    },
    {
        image: bmw3series,
        name: "BMW 3 Series",
        year: 2019,
        brand: "BMW",
        seats: "4 People",
        fuel: "Gasoline",
        km: "8.2km / 1-litre",
        type: "Automatic",
        rent: 350,
    },
    {
        image: volkswagenTcross,
        name: "Volkswagen T-Cross",
        year: 2020,
        brand: "Volkswagen",
        seats: "4 People",
        fuel: "Gasoline",
        km: "5.3km / 1-litre",
        type: "Automatic",
        rent: 400,
    },
    {
        image: cadillacEscalade,
        name: "Cadillac Escalade",
        year: 2020,
        brand: "Cadillac",
        seats: "7 People",
        fuel: "Gasoline",
        km: "7.7km / 1-litre",
        type: "Automatic",
        rent: 620,
    },
    {
        image: bmw4Series,
        name: "BMW 4 Series GTI",
        year: 2021,
        brand: "BMW",
        seats: "4 People",
        fuel: "Gasoline",
        km: "7.6km / 1-litre",
        type: "Automatic",
        rent: 530,
    },
    {
        image: mustang,
        name: "Ford Mustang",
        year: 1967,
        brand: "Ford",
        seats: "2 People",
        fuel: "Electric",
        km: "7.5km / 1-litre",
        type: "Manuel",
        rent: 700,
    },
    {
        image: bmw7series,
        name: "BMW 7 Series",
        year: 2023,
        brand: "BMW",
        seats: "4 People",
        fuel: "Gasoline",
        km: "9km / 1-litre",
        type: "Automatic",
        rent: 550,
    },
    {
        image: bmwi5,
        name: "BMW i5",
        year: 2021,
        brand: "BMW",
        seats: "4 People",
        fuel: "Gasoline",
        km: "10km / 1-litre",
        type: "Automatic",
        rent: 600,
    },
    {
        image: bmwi7,
        name: "BMW i7",
        year: 2022,
        brand: "BMW",
        seats: "4 People",
        fuel: "Electric",
        km: "10km / 1-litre",
        type: "Automatic",
        rent: 650,
    },
    {
        image: bmwM2,
        name: "BMW M2",
        year: 2023,
        brand: "BMW",
        seats: "2 People",
        fuel: "Electric",
        km: "5.6km / 1-litre",
        type: "Automatic",
        rent: 670,
    },

]